name: ozet_haber
description: "KÄ±sa ve net haber"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  auto_route: ^10.2.0
  dio: ^5.9.0
  envied: ^1.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: "^0.14.4"
  flutter_native_splash: ^2.4.6
  auto_route_generator: ^10.2.5
  envied_generator: ^1.3.2
  build_runner: ^2.10.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/transparent_icon.png"
  min_sdk_android: 21  # min:16 - default:21
  remove_alpha_ios: true

flutter_native_splash:
  color: "#262626"
  image: "assets/icon/transparent_icon.png"
  android: true
  ios: true
  android_12:
    icon_background_color: "#262626"
    image: "assets/icon/icon_for_android_12+_splash_screen.png"


flutter:
  uses-material-design: true

  assets:
    - assets/icon/